
modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3"
issueTrackerURL="https://github.com/motivational-dragon/Potion-Blender/issues"
[[mods]]
modId="potionblender"
version="${file.jarVersion}"
displayName="Potion Blender"
displayURL="https://www.curseforge.com/minecraft/mc-mods/potion-blender"
authors="Motivational_Dragon"
description="Potion Blender is a small mod to merge potion effects into one item, allowing for interesting combinations. More info on the mod homepage"

[[dependencies.potionblender]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.potionblender]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
