
modLoader="javafml"
loaderVersion="[${minimum_forge_version},)"
license="GPLv3"
issueTrackerURL="https://github.com/motivational-dragon/Potion-Blender/issues"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/potion-blender"
logoFile = "logo.png"
authors="${mod_author}"
description="${mod_description}"

[[dependencies.potionblender]]
    modId="forge"
    mandatory=true
    versionRange="[${minimum_forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.potionblender]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
